# This file gives the configuration of database to be used in this problem


# by our own convention, we should use only one database
# the parameter to connect to the database is as follows
database_name: grader_pg
# user for initialization  (this user should have all privileges on the datdabase)
init_database_user: grader_pg
init_database_password: grader_pg

# user for running the query (this user should have read-only privileges)
run_database_user: grader_ro
run_database_password: grader_ro
# Each problem can have multiple tables
# However, since there are multiple testcases where
# each testcase should have the same table name.
# We store the data of each testcase into separated table
#
# The SQL of the contestant use the "basic" table name
# and the main function translate the basic table name to the
# "actual" table name stored in the database
# The syntax of translation is as follows
#   %t   will be replaced by testcase.id
table_name_translation:
- student
- registration




